spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.141:3307/test?serverTimezone=UTC&characterEncoding=utf8
      username: root
      password: asdfg12345
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.mybatis: debug